
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Data Workspace
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public sealed class DataWorkspace : global::Microsoft.LightSwitch.Framework.Base.DataWorkspace<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of a DataWorkspace.  Changes can be made to data sources in the new instance independent of changes made to data sources in the default DataWorkspace.
        /// </summary>
        public DataWorkspace() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the Pulsar_DataSource datasource.  This provides members to query and update data in the data source.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.Pulsar_DataSourceService Pulsar_DataSource
        {
            get
            {
                return global::LightSwitchApplication.DataWorkspace.DetailsClass.GetValue(this, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.Pulsar_DataSource);
            }
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspaceDetails<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.Pulsar_DataSource;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataWorkspacePropertySet<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.Pulsar_DataSourceService> Pulsar_DataSource
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties.Pulsar_DataSource) as global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.Pulsar_DataSourceService>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.Pulsar_DataSourceService>.Entry
                    Pulsar_DataSource = new global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.Pulsar_DataSourceService>.Entry(
                        "Pulsar_DataSource",
                        global::LightSwitchApplication.DataWorkspace.DetailsClass.PropertySetProperties._Pulsar_DataSource_Stub);
                private static void _Pulsar_DataSource_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.DataWorkspace.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.Pulsar_DataSourceService>.Data> c, global::LightSwitchApplication.DataWorkspace.DetailsClass d, object sf)
                {
                    c(d, ref d._Pulsar_DataSource, sf);
                }
                 
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataWorkspaceDataServiceProperty<global::LightSwitchApplication.DataWorkspace, global::LightSwitchApplication.DataWorkspace.DetailsClass, global::LightSwitchApplication.Pulsar_DataSourceService>.Data _Pulsar_DataSource;
            
        }
    
        #endregion
    }
    
    #endregion
    
    #region Data Services
    
    /// <summary>
    /// Provides members to query and update data in the Pulsar_DataSource datasource.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    public class Pulsar_DataSource : global::Microsoft.LightSwitch.Framework.Base.DataService<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// This constructor is used for the internal LightSwitch framework. Use DataWorkspace instead.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Pulsar_DataSource() : base()
        {
        }
    
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// Gets the Categories entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Category> Categories
        {
            get
            {
                return global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.GetValue(this, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.PropertySetProperties.Categories);
            }
        }
        
        /// <summary>
        /// Gets the Teams entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Team> Teams
        {
            get
            {
                return global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.GetValue(this, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.PropertySetProperties.Teams);
            }
        }
        
        /// <summary>
        /// Gets the UserInformationLists entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.UserInformationList> UserInformationLists
        {
            get
            {
                return global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.GetValue(this, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.PropertySetProperties.UserInformationLists);
            }
        }
        
        /// <summary>
        /// Gets the Questions entity set.  The entity set provides members to access entities of a specific type.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Question> Questions
        {
            get
            {
                return global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.GetValue(this, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.PropertySetProperties.Questions);
            }
        }
        
        #endregion
    
        #region Queries
    
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Category Categories_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Categories_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Category Categories_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Categories_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Team Teams_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Teams_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Team Teams_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Teams_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.UserInformationList UserInformationLists_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.UserInformationLists_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.UserInformationList UserInformationLists_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.UserInformationLists_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s).
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Question Questions_Single(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Questions_Single.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// Returns the entity whose identity is specified by the parameter(s) or null if no such entity exists.
        /// </summary>
        /// <param name="Id">
        /// The value of the 'Id' key property of the entity to retrieve.
        /// </param>
        public global::LightSwitchApplication.Question Questions_SingleOrDefault(global::System.Nullable<int> Id)
        {
            return this.Details.Methods.Questions_SingleOrDefault.CreateInvocation(Id).Execute();
        }
        
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        /// <param name="SelectedCategory_Parameter">
        /// No Modeled Description Available
        /// </param>
        public global::LightSwitchApplication.Question Query_GetQuestion(string SelectedCategory_Parameter)
        {
            return this.Details.Methods.Query_GetQuestion.CreateInvocation(SelectedCategory_Parameter).Execute();
        }
        
        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceDetails<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.PropertySet, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSet>
        {
    
            static DetailsClass()
            {
                var initializeMethodEntry = global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties.Categories_Single;
                var initializePropertyEntry = global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.PropertySetProperties.Categories;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSet Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class MethodSet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServiceMethodSet<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass>
            {
    
                public MethodSet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Category> Categories_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties.Categories_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Category>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Category> Categories_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties.Categories_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Category>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Team> Teams_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties.Teams_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Team>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Team> Teams_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties.Teams_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Team>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.UserInformationList> UserInformationLists_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties.UserInformationLists_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.UserInformationList>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.UserInformationList> UserInformationLists_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties.UserInformationLists_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.UserInformationList>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question> Questions_Single
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties.Questions_Single) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question> Questions_SingleOrDefault
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties.Questions_SingleOrDefault) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question> Query_GetQuestion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties.Query_GetQuestion) as global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.DataServicePropertySet<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Category> Categories
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.PropertySetProperties.Categories) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Category>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Team> Teams
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.PropertySetProperties.Teams) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Team>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.UserInformationList> UserInformationLists
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.PropertySetProperties.UserInformationLists) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.UserInformationList>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question> Questions
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.PropertySetProperties.Questions) as global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>;
                    }
                }
                
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class MethodSetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Category>.Entry
                    Categories_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Category>.Entry(
                        "Categories_Single",
                        global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties._Categories_Single_Stub);
                private static void _Categories_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Category>.Data> c, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass d, object sf)
                {
                    c(d, ref d._Categories_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Category>.Entry
                    Categories_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Category>.Entry(
                        "Categories_SingleOrDefault",
                        global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties._Categories_SingleOrDefault_Stub);
                private static void _Categories_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Category>.Data> c, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass d, object sf)
                {
                    c(d, ref d._Categories_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Team>.Entry
                    Teams_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Team>.Entry(
                        "Teams_Single",
                        global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties._Teams_Single_Stub);
                private static void _Teams_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Team>.Data> c, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass d, object sf)
                {
                    c(d, ref d._Teams_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Team>.Entry
                    Teams_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Team>.Entry(
                        "Teams_SingleOrDefault",
                        global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties._Teams_SingleOrDefault_Stub);
                private static void _Teams_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Team>.Data> c, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass d, object sf)
                {
                    c(d, ref d._Teams_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.UserInformationList>.Entry
                    UserInformationLists_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.UserInformationList>.Entry(
                        "UserInformationLists_Single",
                        global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties._UserInformationLists_Single_Stub);
                private static void _UserInformationLists_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.UserInformationList>.Data> c, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass d, object sf)
                {
                    c(d, ref d._UserInformationLists_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.UserInformationList>.Entry
                    UserInformationLists_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.UserInformationList>.Entry(
                        "UserInformationLists_SingleOrDefault",
                        global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties._UserInformationLists_SingleOrDefault_Stub);
                private static void _UserInformationLists_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.UserInformationList>.Data> c, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass d, object sf)
                {
                    c(d, ref d._UserInformationLists_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>.Entry
                    Questions_Single = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>.Entry(
                        "Questions_Single",
                        global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties._Questions_Single_Stub);
                private static void _Questions_Single_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>.Data> c, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass d, object sf)
                {
                    c(d, ref d._Questions_Single, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>.Entry
                    Questions_SingleOrDefault = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>.Entry(
                        "Questions_SingleOrDefault",
                        global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties._Questions_SingleOrDefault_Stub);
                private static void _Questions_SingleOrDefault_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>.Data> c, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass d, object sf)
                {
                    c(d, ref d._Questions_SingleOrDefault, sf);
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>.Entry
                    Query_GetQuestion = new global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>.Entry(
                        "Query_GetQuestion",
                        global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.MethodSetProperties._Query_GetQuestion_Stub);
                private static void _Query_GetQuestion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>.Data> c, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass d, object sf)
                {
                    c(d, ref d._Query_GetQuestion, sf);
                }
    
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Category>.Entry
                    Categories = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Category>.Entry(
                        "Categories",
                        global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.PropertySetProperties._Categories_Stub);
                private static void _Categories_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Category>.Data> c, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass d, object sf)
                {
                    c(d, ref d._Categories, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Team>.Entry
                    Teams = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Team>.Entry(
                        "Teams",
                        global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.PropertySetProperties._Teams_Stub);
                private static void _Teams_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Team>.Data> c, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass d, object sf)
                {
                    c(d, ref d._Teams, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.UserInformationList>.Entry
                    UserInformationLists = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.UserInformationList>.Entry(
                        "UserInformationLists",
                        global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.PropertySetProperties._UserInformationLists_Stub);
                private static void _UserInformationLists_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.UserInformationList>.Data> c, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass d, object sf)
                {
                    c(d, ref d._UserInformationLists, sf);
                }
     
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>.Entry
                    Questions = new global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>.Entry(
                        "Questions",
                        global::LightSwitchApplication.Pulsar_DataSource.DetailsClass.PropertySetProperties._Questions_Stub);
                private static void _Questions_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>.Data> c, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass d, object sf)
                {
                    c(d, ref d._Questions, sf);
                }
     
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Category>.Data _Categories;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Team>.Data _Teams;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.UserInformationList>.Data _UserInformationLists;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.DataServiceEntitySetProperty<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>.Data _Questions;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Category>.Data _Categories_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Category>.Data _Categories_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Team>.Data _Teams_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Team>.Data _Teams_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.UserInformationList>.Data _UserInformationLists_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.UserInformationList>.Data _UserInformationLists_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>.Data _Questions_Single;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>.Data _Questions_SingleOrDefault;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.CreateScalarQueryMethod<global::LightSwitchApplication.Pulsar_DataSource, global::LightSwitchApplication.Pulsar_DataSource.DetailsClass, global::LightSwitchApplication.Question>.Data _Query_GetQuestion;
            
        }
    
        #endregion
    }
    
    #endregion
    
}
