

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LightSwitchApplication
{
    #region Entities
    
    /// <summary>
    /// No Modeled Description Available
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
    public sealed partial class Team : global::Microsoft.LightSwitch.Framework.Base.EntityObject<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass>
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new instance of the Team entity.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Team()
            : this(null)
        {
        }
    
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public Team(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Team> entitySet)
            : base(entitySet)
        {
            global::LightSwitchApplication.Team.DetailsClass.Initialize(this);
        }
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Team_Created();
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Team_AllowSaveWithErrors(ref bool result);
    
        #endregion
    
        #region Private Properties
        
        /// <summary>
        /// Gets the Application object for this application.  The Application object provides access to active screens, methods to open screens and access to the current user.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace> Application
        {
            get
            {
                return (global::Microsoft.LightSwitch.IApplication<global::LightSwitchApplication.DataWorkspace>)global::LightSwitchApplication.Application.Current;
            }
        }
        
        /// <summary>
        /// Gets the containing data workspace.  The data workspace provides access to all data sources in the application.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::LightSwitchApplication.DataWorkspace DataWorkspace
        {
            get
            {
                return (global::LightSwitchApplication.DataWorkspace)this.Details.EntitySet.Details.DataService.Details.DataWorkspace;
            }
        }
        
        #endregion
    
        #region Public Properties
    
        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public int Id
        {
            get
            {
                return global::LightSwitchApplication.Team.DetailsClass.GetValue(this, global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.Id);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Id_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ContentType
        {
            get
            {
                return global::LightSwitchApplication.Team.DetailsClass.GetValue(this, global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.ContentType);
            }
            set
            {
                global::LightSwitchApplication.Team.DetailsClass.SetValue(this, global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.ContentType, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContentType_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContentType_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContentType_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Title
        {
            get
            {
                return global::LightSwitchApplication.Team.DetailsClass.GetValue(this, global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.Title);
            }
            set
            {
                global::LightSwitchApplication.Team.DetailsClass.SetValue(this, global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.Title, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Title_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string ContentTypeID
        {
            get
            {
                return global::LightSwitchApplication.Team.DetailsClass.GetValue(this, global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.ContentTypeID);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContentTypeID_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContentTypeID_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ContentTypeID_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> Modified
        {
            get
            {
                return global::LightSwitchApplication.Team.DetailsClass.GetValue(this, global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.Modified);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Modified_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<global::System.DateTime> Created
        {
            get
            {
                return global::LightSwitchApplication.Team.DetailsClass.GetValue(this, global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.Created);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Created_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Nullable<int> Owshiddenversion
        {
            get
            {
                return global::LightSwitchApplication.Team.DetailsClass.GetValue(this, global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.Owshiddenversion);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Owshiddenversion_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Owshiddenversion_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Owshiddenversion_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Version
        {
            get
            {
                return global::LightSwitchApplication.Team.DetailsClass.GetValue(this, global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.Version);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Version_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Version_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Version_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public string Path
        {
            get
            {
                return global::LightSwitchApplication.Team.DetailsClass.GetValue(this, global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.Path);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Path_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Path_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void Path_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.UserInformationList CreatedBy
        {
            get
            {
                return global::LightSwitchApplication.Team.DetailsClass.GetValue(this, global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.CreatedBy);
            }
            set
            {
                global::LightSwitchApplication.Team.DetailsClass.SetValue(this, global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.CreatedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void CreatedBy_Changed();

        /// <summary>
        /// No Modeled Description Available
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::LightSwitchApplication.UserInformationList ModifiedBy
        {
            get
            {
                return global::LightSwitchApplication.Team.DetailsClass.GetValue(this, global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.ModifiedBy);
            }
            set
            {
                global::LightSwitchApplication.Team.DetailsClass.SetValue(this, global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.ModifiedBy, value);
            }
        }
        
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_IsReadOnly(ref bool result);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Validate(global::Microsoft.LightSwitch.EntityValidationResultsBuilder results);
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        partial void ModifiedBy_Changed();

        #endregion
    
        #region Details Class
    
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public sealed class DetailsClass : global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<
                global::LightSwitchApplication.Team,
                global::LightSwitchApplication.Team.DetailsClass,
                global::LightSwitchApplication.Team.DetailsClass.IImplementation,
                global::LightSwitchApplication.Team.DetailsClass.PropertySet,
                global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass>,
                global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass>>
        {
    
            static DetailsClass()
            {
                var initializeEntry = global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.Id;
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private static readonly global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass>.Entry
                __TeamEntry = new global::Microsoft.LightSwitch.Details.Framework.Base.EntityDetails<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass>.Entry(
                    global::LightSwitchApplication.Team.DetailsClass.__Team_CreateNew,
                    global::LightSwitchApplication.Team.DetailsClass.__Team_Created,
                    global::LightSwitchApplication.Team.DetailsClass.__Team_AllowSaveWithErrors);
            private static global::LightSwitchApplication.Team __Team_CreateNew(global::Microsoft.LightSwitch.Framework.EntitySet<global::LightSwitchApplication.Team> es)
            {
                return new global::LightSwitchApplication.Team(es);
            }
            private static void __Team_Created(global::LightSwitchApplication.Team e)
            {
                e.Team_Created();
            }
            private static bool __Team_AllowSaveWithErrors(global::LightSwitchApplication.Team e)
            {
                bool result = false;
                e.Team_AllowSaveWithErrors(ref result);
                return result;
            }
    
            public DetailsClass() : base()
            {
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityCommandSet<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass> Commands
            {
                get
                {
                    return base.Commands;
                }
            }
    
            public new global::Microsoft.LightSwitch.Details.Framework.EntityMethodSet<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass> Methods
            {
                get
                {
                    return base.Methods;
                }
            }
    
            public new global::LightSwitchApplication.Team.DetailsClass.PropertySet Properties
            {
                get
                {
                    return base.Properties;
                }
            }
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public sealed class PropertySet : global::Microsoft.LightSwitch.Details.Framework.Base.EntityPropertySet<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass>
            {
    
                public PropertySet() : base()
                {
                }
    
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, int> Id
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.Id) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, int>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string> ContentType
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.ContentType) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string> Title
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.Title) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string> ContentTypeID
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.ContentTypeID) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::System.Nullable<global::System.DateTime>> Modified
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.Modified) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::System.Nullable<global::System.DateTime>> Created
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.Created) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::System.Nullable<global::System.DateTime>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::System.Nullable<int>> Owshiddenversion
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.Owshiddenversion) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::System.Nullable<int>>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string> Version
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.Version) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string> Path
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.Path) as global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::LightSwitchApplication.UserInformationList> CreatedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.CreatedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::LightSwitchApplication.UserInformationList>;
                    }
                }
                
                public global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::LightSwitchApplication.UserInformationList> ModifiedBy
                {
                    get
                    {
                        return base.GetItem(global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.ModifiedBy) as global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::LightSwitchApplication.UserInformationList>;
                    }
                }
                
            }
    
            #pragma warning disable 109
            [global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1034:NestedTypesShouldNotBeVisible")]
            public interface IImplementation : global::Microsoft.LightSwitch.Internal.IEntityImplementation
            {
                new int Id { get; }
                new string ContentType { get; set; }
                new string Title { get; set; }
                new string ContentTypeID { get; }
                new global::System.Nullable<global::System.DateTime> Modified { get; }
                new global::System.Nullable<global::System.DateTime> Created { get; }
                new global::System.Nullable<int> Owshiddenversion { get; }
                new string Version { get; }
                new string Path { get; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation CreatedBy { get; set; }
                new global::Microsoft.LightSwitch.Internal.IEntityImplementation ModifiedBy { get; set; }
            }
            #pragma warning restore 109
    
            [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
            [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.LightSwitch.BuildTasks.CodeGen", "11.3.0.0")]
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal class PropertySetProperties
            {
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, int>.Entry
                    Id = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, int>.Entry(
                        "Id",
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Id_Stub,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Id_ComputeIsReadOnly,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Id_Validate,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Id_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Id_OnValueChanged);
                private static void _Id_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Team.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, int>.Data> c, global::LightSwitchApplication.Team.DetailsClass d, object sf)
                {
                    c(d, ref d._Id, sf);
                }
                private static bool _Id_ComputeIsReadOnly(global::LightSwitchApplication.Team e)
                {
                    bool result = false;
                    e.Id_IsReadOnly(ref result);
                    return result;
                }
                private static void _Id_Validate(global::LightSwitchApplication.Team e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Id_Validate(r);
                }
                private static int _Id_GetImplementationValue(global::LightSwitchApplication.Team.DetailsClass d)
                {
                    return d.ImplementationEntity.Id;
                }
                private static void _Id_OnValueChanged(global::LightSwitchApplication.Team e)
                {
                    e.Id_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Entry
                    ContentType = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Entry(
                        "ContentType",
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ContentType_Stub,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ContentType_ComputeIsReadOnly,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ContentType_Validate,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ContentType_GetImplementationValue,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ContentType_SetImplementationValue,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ContentType_OnValueChanged);
                private static void _ContentType_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Team.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Data> c, global::LightSwitchApplication.Team.DetailsClass d, object sf)
                {
                    c(d, ref d._ContentType, sf);
                }
                private static bool _ContentType_ComputeIsReadOnly(global::LightSwitchApplication.Team e)
                {
                    bool result = false;
                    e.ContentType_IsReadOnly(ref result);
                    return result;
                }
                private static void _ContentType_Validate(global::LightSwitchApplication.Team e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ContentType_Validate(r);
                }
                private static string _ContentType_GetImplementationValue(global::LightSwitchApplication.Team.DetailsClass d)
                {
                    return d.ImplementationEntity.ContentType;
                }
                private static void _ContentType_SetImplementationValue(global::LightSwitchApplication.Team.DetailsClass d, string v)
                {
                    d.ImplementationEntity.ContentType = v;
                }
                private static void _ContentType_OnValueChanged(global::LightSwitchApplication.Team e)
                {
                    e.ContentType_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Entry
                    Title = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Entry(
                        "Title",
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Title_Stub,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Title_ComputeIsReadOnly,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Title_Validate,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Title_GetImplementationValue,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Title_SetImplementationValue,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Title_OnValueChanged);
                private static void _Title_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Team.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Data> c, global::LightSwitchApplication.Team.DetailsClass d, object sf)
                {
                    c(d, ref d._Title, sf);
                }
                private static bool _Title_ComputeIsReadOnly(global::LightSwitchApplication.Team e)
                {
                    bool result = false;
                    e.Title_IsReadOnly(ref result);
                    return result;
                }
                private static void _Title_Validate(global::LightSwitchApplication.Team e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Title_Validate(r);
                }
                private static string _Title_GetImplementationValue(global::LightSwitchApplication.Team.DetailsClass d)
                {
                    return d.ImplementationEntity.Title;
                }
                private static void _Title_SetImplementationValue(global::LightSwitchApplication.Team.DetailsClass d, string v)
                {
                    d.ImplementationEntity.Title = v;
                }
                private static void _Title_OnValueChanged(global::LightSwitchApplication.Team e)
                {
                    e.Title_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Entry
                    ContentTypeID = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Entry(
                        "ContentTypeID",
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ContentTypeID_Stub,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ContentTypeID_ComputeIsReadOnly,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ContentTypeID_Validate,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ContentTypeID_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ContentTypeID_OnValueChanged);
                private static void _ContentTypeID_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Team.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Data> c, global::LightSwitchApplication.Team.DetailsClass d, object sf)
                {
                    c(d, ref d._ContentTypeID, sf);
                }
                private static bool _ContentTypeID_ComputeIsReadOnly(global::LightSwitchApplication.Team e)
                {
                    bool result = false;
                    e.ContentTypeID_IsReadOnly(ref result);
                    return result;
                }
                private static void _ContentTypeID_Validate(global::LightSwitchApplication.Team e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ContentTypeID_Validate(r);
                }
                private static string _ContentTypeID_GetImplementationValue(global::LightSwitchApplication.Team.DetailsClass d)
                {
                    return d.ImplementationEntity.ContentTypeID;
                }
                private static void _ContentTypeID_OnValueChanged(global::LightSwitchApplication.Team e)
                {
                    e.ContentTypeID_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    Modified = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "Modified",
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Modified_Stub,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Modified_ComputeIsReadOnly,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Modified_Validate,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Modified_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Modified_OnValueChanged);
                private static void _Modified_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Team.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.Team.DetailsClass d, object sf)
                {
                    c(d, ref d._Modified, sf);
                }
                private static bool _Modified_ComputeIsReadOnly(global::LightSwitchApplication.Team e)
                {
                    bool result = false;
                    e.Modified_IsReadOnly(ref result);
                    return result;
                }
                private static void _Modified_Validate(global::LightSwitchApplication.Team e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Modified_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _Modified_GetImplementationValue(global::LightSwitchApplication.Team.DetailsClass d)
                {
                    return d.ImplementationEntity.Modified;
                }
                private static void _Modified_OnValueChanged(global::LightSwitchApplication.Team e)
                {
                    e.Modified_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry
                    Created = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::System.Nullable<global::System.DateTime>>.Entry(
                        "Created",
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Created_Stub,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Created_ComputeIsReadOnly,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Created_Validate,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Created_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Created_OnValueChanged);
                private static void _Created_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Team.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data> c, global::LightSwitchApplication.Team.DetailsClass d, object sf)
                {
                    c(d, ref d._Created, sf);
                }
                private static bool _Created_ComputeIsReadOnly(global::LightSwitchApplication.Team e)
                {
                    bool result = false;
                    e.Created_IsReadOnly(ref result);
                    return result;
                }
                private static void _Created_Validate(global::LightSwitchApplication.Team e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Created_Validate(r);
                }
                private static global::System.Nullable<global::System.DateTime> _Created_GetImplementationValue(global::LightSwitchApplication.Team.DetailsClass d)
                {
                    return d.ImplementationEntity.Created;
                }
                private static void _Created_OnValueChanged(global::LightSwitchApplication.Team e)
                {
                    e.Created_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::System.Nullable<int>>.Entry
                    Owshiddenversion = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::System.Nullable<int>>.Entry(
                        "Owshiddenversion",
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Owshiddenversion_Stub,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Owshiddenversion_ComputeIsReadOnly,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Owshiddenversion_Validate,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Owshiddenversion_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Owshiddenversion_OnValueChanged);
                private static void _Owshiddenversion_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Team.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::System.Nullable<int>>.Data> c, global::LightSwitchApplication.Team.DetailsClass d, object sf)
                {
                    c(d, ref d._Owshiddenversion, sf);
                }
                private static bool _Owshiddenversion_ComputeIsReadOnly(global::LightSwitchApplication.Team e)
                {
                    bool result = false;
                    e.Owshiddenversion_IsReadOnly(ref result);
                    return result;
                }
                private static void _Owshiddenversion_Validate(global::LightSwitchApplication.Team e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Owshiddenversion_Validate(r);
                }
                private static global::System.Nullable<int> _Owshiddenversion_GetImplementationValue(global::LightSwitchApplication.Team.DetailsClass d)
                {
                    return d.ImplementationEntity.Owshiddenversion;
                }
                private static void _Owshiddenversion_OnValueChanged(global::LightSwitchApplication.Team e)
                {
                    e.Owshiddenversion_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Entry
                    Version = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Entry(
                        "Version",
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Version_Stub,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Version_ComputeIsReadOnly,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Version_Validate,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Version_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Version_OnValueChanged);
                private static void _Version_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Team.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Data> c, global::LightSwitchApplication.Team.DetailsClass d, object sf)
                {
                    c(d, ref d._Version, sf);
                }
                private static bool _Version_ComputeIsReadOnly(global::LightSwitchApplication.Team e)
                {
                    bool result = false;
                    e.Version_IsReadOnly(ref result);
                    return result;
                }
                private static void _Version_Validate(global::LightSwitchApplication.Team e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Version_Validate(r);
                }
                private static string _Version_GetImplementationValue(global::LightSwitchApplication.Team.DetailsClass d)
                {
                    return d.ImplementationEntity.Version;
                }
                private static void _Version_OnValueChanged(global::LightSwitchApplication.Team e)
                {
                    e.Version_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Entry
                    Path = new global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Entry(
                        "Path",
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Path_Stub,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Path_ComputeIsReadOnly,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Path_Validate,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Path_GetImplementationValue,
                        null,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._Path_OnValueChanged);
                private static void _Path_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Team.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Data> c, global::LightSwitchApplication.Team.DetailsClass d, object sf)
                {
                    c(d, ref d._Path, sf);
                }
                private static bool _Path_ComputeIsReadOnly(global::LightSwitchApplication.Team e)
                {
                    bool result = false;
                    e.Path_IsReadOnly(ref result);
                    return result;
                }
                private static void _Path_Validate(global::LightSwitchApplication.Team e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.Path_Validate(r);
                }
                private static string _Path_GetImplementationValue(global::LightSwitchApplication.Team.DetailsClass d)
                {
                    return d.ImplementationEntity.Path;
                }
                private static void _Path_OnValueChanged(global::LightSwitchApplication.Team e)
                {
                    e.Path_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::LightSwitchApplication.UserInformationList>.Entry
                    CreatedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::LightSwitchApplication.UserInformationList>.Entry(
                        "CreatedBy",
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._CreatedBy_Stub,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._CreatedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._CreatedBy_Validate,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._CreatedBy_GetCoreImplementationValue,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._CreatedBy_GetImplementationValue,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._CreatedBy_SetImplementationValue,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._CreatedBy_Refresh,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._CreatedBy_OnValueChanged);
                private static void _CreatedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Team.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::LightSwitchApplication.UserInformationList>.Data> c, global::LightSwitchApplication.Team.DetailsClass d, object sf)
                {
                    c(d, ref d._CreatedBy, sf);
                }
                private static bool _CreatedBy_ComputeIsReadOnly(global::LightSwitchApplication.Team e)
                {
                    bool result = false;
                    e.CreatedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _CreatedBy_Validate(global::LightSwitchApplication.Team e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.CreatedBy_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _CreatedBy_GetCoreImplementationValue(global::LightSwitchApplication.Team.DetailsClass d)
                {
                    return d.ImplementationEntity.CreatedBy;
                }
                private static global::LightSwitchApplication.UserInformationList _CreatedBy_GetImplementationValue(global::LightSwitchApplication.Team.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.UserInformationList, global::LightSwitchApplication.UserInformationList.DetailsClass>(global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.CreatedBy, ref d._CreatedBy);
                }
                private static void _CreatedBy_SetImplementationValue(global::LightSwitchApplication.Team.DetailsClass d, global::LightSwitchApplication.UserInformationList v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.CreatedBy, ref d._CreatedBy, (i, ev) => i.CreatedBy = ev, v);
                }
                private static void _CreatedBy_Refresh(global::LightSwitchApplication.Team.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.CreatedBy, ref d._CreatedBy);
                }
                private static void _CreatedBy_OnValueChanged(global::LightSwitchApplication.Team e)
                {
                    e.CreatedBy_Changed();
                }
    
                [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
                public static readonly global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::LightSwitchApplication.UserInformationList>.Entry
                    ModifiedBy = new global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::LightSwitchApplication.UserInformationList>.Entry(
                        "ModifiedBy",
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ModifiedBy_Stub,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ModifiedBy_ComputeIsReadOnly,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ModifiedBy_Validate,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ModifiedBy_GetCoreImplementationValue,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ModifiedBy_GetImplementationValue,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ModifiedBy_SetImplementationValue,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ModifiedBy_Refresh,
                        global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties._ModifiedBy_OnValueChanged);
                private static void _ModifiedBy_Stub(global::Microsoft.LightSwitch.Details.Framework.Base.DetailsCallback<global::LightSwitchApplication.Team.DetailsClass, global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::LightSwitchApplication.UserInformationList>.Data> c, global::LightSwitchApplication.Team.DetailsClass d, object sf)
                {
                    c(d, ref d._ModifiedBy, sf);
                }
                private static bool _ModifiedBy_ComputeIsReadOnly(global::LightSwitchApplication.Team e)
                {
                    bool result = false;
                    e.ModifiedBy_IsReadOnly(ref result);
                    return result;
                }
                private static void _ModifiedBy_Validate(global::LightSwitchApplication.Team e, global::Microsoft.LightSwitch.EntityValidationResultsBuilder r)
                {
                    e.ModifiedBy_Validate(r);
                }
                private static global::Microsoft.LightSwitch.Internal.IEntityImplementation _ModifiedBy_GetCoreImplementationValue(global::LightSwitchApplication.Team.DetailsClass d)
                {
                    return d.ImplementationEntity.ModifiedBy;
                }
                private static global::LightSwitchApplication.UserInformationList _ModifiedBy_GetImplementationValue(global::LightSwitchApplication.Team.DetailsClass d)
                {
                    return d.GetImplementationValue<global::LightSwitchApplication.UserInformationList, global::LightSwitchApplication.UserInformationList.DetailsClass>(global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.ModifiedBy, ref d._ModifiedBy);
                }
                private static void _ModifiedBy_SetImplementationValue(global::LightSwitchApplication.Team.DetailsClass d, global::LightSwitchApplication.UserInformationList v)
                {
                    d.SetImplementationValue(global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.ModifiedBy, ref d._ModifiedBy, (i, ev) => i.ModifiedBy = ev, v);
                }
                private static void _ModifiedBy_Refresh(global::LightSwitchApplication.Team.DetailsClass d)
                {
                    d.RefreshNavigationProperty(global::LightSwitchApplication.Team.DetailsClass.PropertySetProperties.ModifiedBy, ref d._ModifiedBy);
                }
                private static void _ModifiedBy_OnValueChanged(global::LightSwitchApplication.Team e)
                {
                    e.ModifiedBy_Changed();
                }
    
            }
    
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, int>.Data _Id;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Data _ContentType;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Data _Title;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Data _ContentTypeID;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _Modified;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::System.Nullable<global::System.DateTime>>.Data _Created;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::System.Nullable<int>>.Data _Owshiddenversion;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Data _Version;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityStorageProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, string>.Data _Path;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::LightSwitchApplication.UserInformationList>.Data _CreatedBy;
            
            [global::System.Diagnostics.DebuggerBrowsable(global::System.Diagnostics.DebuggerBrowsableState.Never)]
            private global::Microsoft.LightSwitch.Details.Framework.EntityReferenceProperty<global::LightSwitchApplication.Team, global::LightSwitchApplication.Team.DetailsClass, global::LightSwitchApplication.UserInformationList>.Data _ModifiedBy;
            
        }
    
        #endregion
    }
    
    #endregion
}
